M48
; DRILL file {KiCad (7.0.0-0)} date Monday, May 15, 2023 at 11:59:23 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-15T11:59:23-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0886
%
G90
G05
T1
X4.7483Y-2.6565
X4.7483Y-2.7565
X4.7483Y-2.8565
T2
X5.087Y-2.598
X5.087Y-2.7555
X5.087Y-2.913
T0
M30
