M48
; DRILL file {KiCad (7.0.0-0)} date Monday, May 15, 2023 at 11:59:50 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-15T11:59:50-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1614
%
G90
G05
T1
X4.133Y-2.166
X4.1339Y-5.315
X4.8198Y-3.7402
X5.7087Y-2.1654
X5.7087Y-5.315
T2
X4.0863Y-4.2065
X4.0962Y-4.9939
T0
M30
